// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfwiHJna-pOUf9NBgwBoUcXiqt7N8AGAM',
    appId: '1:645493220772:web:19aa03e298d334a3058d31',
    messagingSenderId: '645493220772',
    projectId: 'chat-room-22210',
    authDomain: 'chat-room-22210.firebaseapp.com',
    storageBucket: 'chat-room-22210.firebasestorage.app',
    measurementId: 'G-J9TMV1LVCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSRj6l5iNCNl-HtODRGE596H0v0UJJwoA',
    appId: '1:645493220772:android:b62216f651e620df058d31',
    messagingSenderId: '645493220772',
    projectId: 'chat-room-22210',
    storageBucket: 'chat-room-22210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ZK8iXIHhImXB7qDS-uI76wGm9m8L1a4',
    appId: '1:645493220772:ios:22a415d11b280cb7058d31',
    messagingSenderId: '645493220772',
    projectId: 'chat-room-22210',
    storageBucket: 'chat-room-22210.firebasestorage.app',
    iosBundleId: 'com.example.wellorgsAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ZK8iXIHhImXB7qDS-uI76wGm9m8L1a4',
    appId: '1:645493220772:ios:22a415d11b280cb7058d31',
    messagingSenderId: '645493220772',
    projectId: 'chat-room-22210',
    storageBucket: 'chat-room-22210.firebasestorage.app',
    iosBundleId: 'com.example.wellorgsAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfwiHJna-pOUf9NBgwBoUcXiqt7N8AGAM',
    appId: '1:645493220772:web:f9edb32f9eb2b49e058d31',
    messagingSenderId: '645493220772',
    projectId: 'chat-room-22210',
    authDomain: 'chat-room-22210.firebaseapp.com',
    storageBucket: 'chat-room-22210.firebasestorage.app',
    measurementId: 'G-36D76CYHKJ',
  );
}
